apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "FMBhj6p7FIbSPzZxko83hsZSB3TBAknj0AIRB77+nep+hnEBK75aHXJ/eBEOQ0hK\nYtMXt1PTGA4i8aciv1FsqsCKiMVH/OwnhBOTf5ZAqTrbYHrwuPQ+5xPCZLpEIA+h\nuMRR9AFtpiIJhJhrx7f8J57v9xuIVQ9KkoePvFl52a0="
