apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "VhYW/H9JYviiKzGHYcJDMNVOz1PLl4XRbKA/SCCfsQ6lLfxRaXg+LdzvT6JGpwud\nvG9toZSIttwgUCtBH6YBCK/oY42a23I+72pEnMdpktEGU7YChQjzEOSv7Hg3kCOV\nYt1ATERmyqLnx5zWUPwAhphUN2L1HlllqdtVcurvSm4="
