apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "7ELh38Dg+oyrarlBxSiEZjQUXQnGbLol+z5+46Pop8qAudoPnUkP1Wc163sMZOZr\nWqIEJdtFf5G2U2T4TgJPJKqlQuIrDQTrIIDNHeoa6nTT4sql5j4By1iI2HA6peiL\nywfRVKbqp3mfo4Id3uuqb4UTY6rXnBRl+wZCQ3bQliU="
